site_name: Buildarr Prowlarr Plugin

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Release Notes: "release-notes.md"
  - Configuration:
    - Host Configuration: "configuration/host.md"
    - Indexers: "configuration/indexers.md"
    - Apps: "configuration/apps.md"
    - Download Clients: "configuration/download-clients.md"
    - Notifications: "configuration/notifications.md"
    - Tags: "configuration/tags.md"
    - General: "configuration/general.md"
    - UI: "configuration/ui.md"
  - Buildarr: "https://buildarr.github.io"

watch:
  - buildarr_buildarr
